"""Initial migration.

Revision ID: bd9125b32243
Revises: c828671bd248
Create Date: 2025-02-09 19:04:50.414335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9125b32243'
down_revision = 'c828671bd248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.String(length=100), nullable=False))

    with op.batch_alter_table('exit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exit', schema=None) as batch_op:
        batch_op.drop_column('local')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('local')

    # ### end Alembic commands ###
