"""Initial migration.

Revision ID: c828671bd248
Revises: cd1431c6c0e8
Create Date: 2025-02-09 18:50:19.260308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c828671bd248'
down_revision = 'cd1431c6c0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('product_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('product_type')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
